Traceback (most recent call last):
  File "C:\Users\ivcbibl13\Python\mirea\practice\third.py", line 45, in delete
    math.log(z)
ValueError: math domain error
