Traceback (most recent call last):
  File "C:\Users\aidar\PycharmProjects\Python\mirea\practice\third.py", line 52, in delete
    math.log(z)
ValueError: math domain error
